per_listener_settings true

listener 1883
allow_anonymous true
max_keepalive 65535
max_inflight_messages 20
max_queued_messages 1000

persistence true
persistence_location /mosquitto/data/

autosave_interval 1800

log_type all
log_dest file /mosquitto/log/mosquitto.log

retain_available true
max_retained_messages 2000

set_tcp_nodelay true
